version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bibliotheque-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Bibliotheque
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./database/seed.sql:/docker-entrypoint-initdb.d/init.sql
